### ISSUE TITLE
Tools/MapExtractor

### ISSUE THREAD

**Issue by ntlf9t** [Devir7/Legion_Proyect#1]
MapExtractor failure,Whether DATA LINK can be provided.

The following links are invalid:
CLIENTES LINK Descarga cliente completo desde FTP: ftp://10.97.1.12/Clientes%20de%20WOW/Legion%207.3.5%20%2026124.rar Descargar rund and play http://www.mediafire.com/file/fpsbts93ka2q0g5/Rund_and_play_BlackCore.rar/file Este cliente se va descargando mientras se juega.

DATA LINK oficiales 26124 https://www.mediafire.com/file/tbvzrzbda7xrnq6/data_7.3.5.7z/file

**Comment by Devir7** [comment]
Sorry I couldn't answer right away, I didn't see the notification. I got the map files from here
[DATA](https://github.com/dufernst/LegionCore-7.3.5/issues/101)

**Comment by ntlf9t** [comment]
thank you
